/*                   CREATE DATABASE                   */

DROP DATABASE bpc;
CREATE SCHEMA bpc;
USE bpc;

/* 
    
    SET SQL_SAFE_UPDATES = 0; 

    SAFE_UPDATES WILL CAUSE ISSUE LATER WHEN TRYING TO PUSH IT TO CUSTOMERS. 
    IT RESETS WITH EACH CONNECTION MEANING LEAVING THE CONNECTION OPEN, WILL ALLOW THE USER TO MAKE CHANGES.
    SO WHILE THE UI IS OPEN THERE SHOULD BE A CONTINUOUS CONNECTION ENSURING THAT THE PROGRAM WILL FUNCTION
    AS INTENDED.

*/